// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_aspectratiopixmaplabel.cpp"
#include "EWIEGA46WW/moc_creatingtestform.cpp"
#include "EWIEGA46WW/moc_dialogforcreatingform.cpp"
#include "EWIEGA46WW/moc_menuwindow.cpp"
#include "EWIEGA46WW/moc_qrightclickbutton.cpp"
#include "EWIEGA46WW/moc_testwidget.cpp"
